export const RestaurantList = [
    {
      info: {
        id: "694646",
        name: "Pizza Hut",
        cloudinaryImageId:
          "RX_THUMBNAIL/IMAGES/VENDOR/2024/7/18/8a3966de-89e8-4e04-ae4c-a5f5d2245633_694646.jpg",
        locality: "Lotus Park",
        areaName: "Ambegaon",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4.1,
        parentId: "721",
        avgRatingString: "4.1",
        totalRatingsString: "1.1K+",
        sla: {
          deliveryTime: 41,
          lastMileTravel: 1.8,
          serviceability: "SERVICEABLE",
          slaString: "40-45 mins",
          lastMileTravelString: "1.8 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: { nextCloseTime: "2024-11-20 05:00:00", opened: true },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        aggregatedDiscountInfoV3: { header: "50% OFF", subHeader: "UPTO ₹100" },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: { lottie: {}, video: {} },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
        externalRatings: { aggregatedRating: { rating: "--" } },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
      },
      analytics: { context: "seo-data-2b3cc11c-e3ea-4faa-ac76-6e43fd08e2d0" },
      cta: {
        link: "https://www.swiggy.com/city/pune/pizza-hut-lotus-park-ambegaon-rest694646",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "430767",
        name: "Domino's Pizza",
        cloudinaryImageId:
          "RX_THUMBNAIL/IMAGES/VENDOR/2024/10/24/7f53d41c-21b8-4a8f-be60-07eec870ee92_430767.JPG",
        locality: "Yash Ganga Residency",
        areaName: "Sinhgad Road",
        costForTwo: "₹400 for two",
        cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
        avgRating: 4,
        parentId: "2456",
        avgRatingString: "4.0",
        totalRatingsString: "2.1K+",
        sla: {
          deliveryTime: 25,
          lastMileTravel: 2.2,
          serviceability: "SERVICEABLE",
          slaString: "20-25 mins",
          lastMileTravelString: "2.2 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: { nextCloseTime: "2024-11-20 02:59:00", opened: true },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹1199",
          discountTag: "FLAT DEAL",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: { lottie: {}, video: {} },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
        externalRatings: { aggregatedRating: { rating: "--" } },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
      },
      analytics: { context: "seo-data-2b3cc11c-e3ea-4faa-ac76-6e43fd08e2d0" },
      cta: {
        link: "https://www.swiggy.com/city/pune/dominos-pizza-yash-ganga-residency-sinhgad-road-rest430767",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "255155",
        name: "LunchBox - Meals and Thalis",
        cloudinaryImageId:
          "RX_THUMBNAIL/IMAGES/VENDOR/2024/10/16/781c0537-7caf-43dd-8467-a6e09af6fc80_255155.jpg",
        locality: "Datta nagar chowk",
        areaName: "Ambegaon",
        costForTwo: "₹200 for two",
        cuisines: [
          "Biryani",
          "North Indian",
          "Punjabi",
          "Healthy Food",
          "Desserts",
          "Beverages",
        ],
        avgRating: 4.3,
        parentId: "4925",
        avgRatingString: "4.3",
        totalRatingsString: "2.0K+",
        sla: {
          deliveryTime: 37,
          lastMileTravel: 2.7,
          serviceability: "SERVICEABLE",
          slaString: "35-40 mins",
          lastMileTravelString: "2.7 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: { nextCloseTime: "2024-11-19 23:59:00", opened: true },
        badges: {
          textExtendedBadges: [
            {
              iconId: "guiltfree/GF_Logo_android_3x",
              shortDescription: "options available",
              fontColor: "#7E808C",
            },
          ],
        },
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {
              badgeObject: [
                {
                  attributes: {
                    description: "",
                    fontColor: "#7E808C",
                    iconId: "guiltfree/GF_Logo_android_3x",
                    shortDescription: "options available",
                  },
                },
              ],
            },
          },
        },
        aggregatedDiscountInfoV3: { header: "ITEMS", subHeader: "AT ₹159" },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: { lottie: {}, video: {} },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
        externalRatings: { aggregatedRating: { rating: "--" } },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
      },
      analytics: { context: "seo-data-2b3cc11c-e3ea-4faa-ac76-6e43fd08e2d0" },
      cta: {
        link: "https://www.swiggy.com/city/pune/lunchbox-meals-and-thalis-datta-nagar-chowk-ambegaon-rest255155",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "46005",
        name: "McDonald's",
        cloudinaryImageId:
          "RX_THUMBNAIL/IMAGES/VENDOR/2024/9/18/400085df-6ccb-4715-832a-ec36f9daf486_46005.jpg",
        locality: "Dhankawdi",
        areaName: "Dhankawdi",
        costForTwo: "₹400 for two",
        cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
        avgRating: 4.5,
        parentId: "630",
        avgRatingString: "4.5",
        totalRatingsString: "20K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 2,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "2.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: { nextCloseTime: "2024-11-19 23:59:00", opened: true },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹549",
          discountTag: "FLAT DEAL",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: { lottie: {}, video: {} },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
        externalRatings: {
          aggregatedRating: { rating: "4.4", ratingCount: "6.5K+" },
          source: "GOOGLE",
          sourceIconImageId: "v1704440323/google_ratings/rating_google_tag",
        },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
      },
      analytics: { context: "seo-data-2b3cc11c-e3ea-4faa-ac76-6e43fd08e2d0" },
      cta: {
        link: "https://www.swiggy.com/city/pune/mcdonalds-dhankawdi-rest46005",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "77745",
        name: "Hotel Al Zaika",
        cloudinaryImageId: "mohc5yfyaxudlgtda65x",
        locality: "Vadgaon Budruk",
        areaName: "Narhe",
        costForTwo: "₹500 for two",
        cuisines: ["Indian", "Punjabi"],
        avgRating: 4.2,
        parentId: "97829",
        avgRatingString: "4.2",
        totalRatingsString: "5.4K+",
        sla: {
          deliveryTime: 34,
          lastMileTravel: 2.3,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "2.3 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: { nextCloseTime: "2024-11-19 23:30:00", opened: true },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        aggregatedDiscountInfoV3: { header: "70% OFF", discountTag: "FLAT DEAL" },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: { lottie: {}, video: {} },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
        externalRatings: { aggregatedRating: { rating: "--" } },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
      },
      analytics: { context: "seo-data-2b3cc11c-e3ea-4faa-ac76-6e43fd08e2d0" },
      cta: {
        link: "https://www.swiggy.com/city/pune/hotel-al-zaika-vadgaon-budruk-narhe-rest77745",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "717982",
        name: "Burger King",
        cloudinaryImageId:
          "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/11/60497022-434e-4d21-bc0e-813fea770ae5_717982.JPG",
        locality: "Lotus Park 3",
        areaName: "Ambegaon",
        costForTwo: "₹350 for two",
        cuisines: ["Burgers", "American"],
        avgRating: 4.2,
        parentId: "166",
        avgRatingString: "4.2",
        totalRatingsString: "4.1K+",
        sla: {
          deliveryTime: 35,
          lastMileTravel: 1.7,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "1.7 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: { nextCloseTime: "2024-11-20 03:55:00", opened: true },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        aggregatedDiscountInfoV3: { header: "ITEMS", subHeader: "AT ₹99" },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: { lottie: {}, video: {} },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
        externalRatings: { aggregatedRating: { rating: "--" } },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
      },
      analytics: { context: "seo-data-2b3cc11c-e3ea-4faa-ac76-6e43fd08e2d0" },
      cta: {
        link: "https://www.swiggy.com/city/pune/burger-king-lotus-park-3-ambegaon-rest717982",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "752224",
        name: "Theobroma",
        cloudinaryImageId:
          "RX_THUMBNAIL/IMAGES/VENDOR/2024/11/18/465df759-6c8b-4210-a1d8-358d6e9a2b60_752224.JPG",
        locality: "HINGANE KHURD",
        areaName: "Sinhgad Road",
        costForTwo: "₹400 for two",
        cuisines: ["Bakery", "Desserts"],
        avgRating: 4.5,
        parentId: "1040",
        avgRatingString: "4.5",
        totalRatingsString: "691",
        sla: {
          deliveryTime: 35,
          lastMileTravel: 3.9,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "3.9 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: { nextCloseTime: "2024-11-19 23:59:00", opened: true },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        aggregatedDiscountInfoV3: { header: "50% OFF", subHeader: "UPTO ₹100" },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: { lottie: {}, video: {} },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
        externalRatings: { aggregatedRating: { rating: "--" } },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
      },
      analytics: { context: "seo-data-2b3cc11c-e3ea-4faa-ac76-6e43fd08e2d0" },
      cta: {
        link: "https://www.swiggy.com/city/pune/theobroma-hingane-khurd-sinhgad-road-rest752224",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "22378",
        name: "Ganesh Bhel",
        cloudinaryImageId: "zyrpuweruyaryow9ovd7",
        locality: "Manik Baug",
        areaName: "Sinhgad Road",
        costForTwo: "₹100 for two",
        cuisines: ["Street Food"],
        avgRating: 4.5,
        veg: true,
        parentId: "1772",
        avgRatingString: "4.5",
        totalRatingsString: "12K+",
        sla: {
          deliveryTime: 29,
          lastMileTravel: 2.5,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "2.5 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: { nextCloseTime: "2024-11-19 22:30:00", opened: true },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: { lottie: {}, video: {} },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
        externalRatings: { aggregatedRating: { rating: "--" } },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
      },
      analytics: { context: "seo-data-2b3cc11c-e3ea-4faa-ac76-6e43fd08e2d0" },
      cta: {
        link: "https://www.swiggy.com/city/pune/ganesh-bhel-manik-baug-sinhgad-road-rest22378",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "395313",
        name: "McDonald's Gourmet Burger Collection",
        cloudinaryImageId: "k84eau7nrimvny2z2bqg",
        locality: "Ambegaon Budruk",
        areaName: "Dhankawadi",
        costForTwo: "₹600 for two",
        cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
        avgRating: 4.6,
        parentId: "10761",
        avgRatingString: "4.6",
        totalRatingsString: "305",
        sla: {
          deliveryTime: 29,
          lastMileTravel: 2,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "2.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: { nextCloseTime: "2024-11-20 01:45:00", opened: true },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        aggregatedDiscountInfoV3: { header: "50% OFF", subHeader: "UPTO ₹100" },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: { lottie: {}, video: {} },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
        externalRatings: { aggregatedRating: { rating: "--" } },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
      },
      analytics: { context: "seo-data-2b3cc11c-e3ea-4faa-ac76-6e43fd08e2d0" },
      cta: {
        link: "https://www.swiggy.com/city/pune/mcdonalds-gourmet-burger-collection-ambegaon-budruk-dhankawadi-rest395313",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "382689",
        name: "Gourmet Ice Cream Cakes by Baskin Robbins",
        cloudinaryImageId: "d679c532ca07a6f3fd6d89d603861412",
        locality: "Manik Baug",
        areaName: "Sinhgad Road",
        costForTwo: "₹250 for two",
        cuisines: ["Desserts", "Ice Cream", "Bakery"],
        avgRating: 4.5,
        veg: true,
        parentId: "21932",
        avgRatingString: "4.5",
        totalRatingsString: "31",
        sla: {
          deliveryTime: 35,
          lastMileTravel: 2.3,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "2.3 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: { nextCloseTime: "2024-11-20 00:30:00", opened: true },
        badges: {
          imageBadges: [
            {
              imageId: "v1695133679/badges/Pure_Veg111.png",
              description: "pureveg",
            },
          ],
        },
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {
              badgeObject: [
                {
                  attributes: {
                    description: "pureveg",
                    imageId: "v1695133679/badges/Pure_Veg111.png",
                  },
                },
              ],
            },
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: { header: "50% OFF", subHeader: "UPTO ₹100" },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: { lottie: {}, video: {} },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
        externalRatings: { aggregatedRating: { rating: "--" } },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
      },
      analytics: { context: "seo-data-2b3cc11c-e3ea-4faa-ac76-6e43fd08e2d0" },
      cta: {
        link: "https://www.swiggy.com/city/pune/gourmet-ice-cream-cakes-by-baskin-robbins-manik-baug-sinhgad-road-rest382689",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "792348",
        name: "Wendy's Flavor Fresh Burgers",
        cloudinaryImageId: "f1aa621021a2826088089b89842d4e7c",
        locality: "Datta nagar chowk",
        areaName: "AVDHOOT HIGHTS",
        costForTwo: "₹500 for two",
        cuisines: ["Burgers", "American", "Fast Food", "Snacks", "Beverages"],
        avgRating: 4.2,
        parentId: "470493",
        avgRatingString: "4.2",
        totalRatingsString: "27",
        sla: {
          deliveryTime: 36,
          lastMileTravel: 2.7,
          serviceability: "SERVICEABLE",
          slaString: "35-40 mins",
          lastMileTravelString: "2.7 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: { nextCloseTime: "2024-11-19 23:59:00", opened: true },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        aggregatedDiscountInfoV3: { header: "30% OFF", subHeader: "UPTO ₹75" },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: { lottie: {}, video: {} },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
        externalRatings: { aggregatedRating: { rating: "--" } },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
      },
      analytics: { context: "seo-data-2b3cc11c-e3ea-4faa-ac76-6e43fd08e2d0" },
      cta: {
        link: "https://www.swiggy.com/city/pune/wendys-flavor-fresh-burgers-datta-nagar-chowk-avdhoot-hights-rest792348",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "643841",
        name: "WeFit - Protein Bowls, Salads & Sandwiches",
        cloudinaryImageId:
          "RX_THUMBNAIL/IMAGES/VENDOR/2024/9/30/8a772a6e-b426-45ec-a2f1-be98bc6683aa_643841.JPG",
        locality: "Ventual College",
        areaName: "Wadgaon",
        costForTwo: "₹250 for two",
        cuisines: ["Healthy Food", "Salads", "Keto", "Snacks"],
        avgRating: 4.8,
        parentId: "355285",
        avgRatingString: "4.8",
        totalRatingsString: "700",
        sla: {
          deliveryTime: 25,
          lastMileTravel: 3.6,
          serviceability: "SERVICEABLE",
          slaString: "20-30 mins",
          lastMileTravelString: "3.6 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: { nextCloseTime: "2024-11-20 02:00:00", opened: true },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        aggregatedDiscountInfoV3: { header: "50% OFF", subHeader: "UPTO ₹100" },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: { lottie: {}, video: {} },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
        externalRatings: { aggregatedRating: { rating: "--" } },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
      },
      analytics: { context: "seo-data-2b3cc11c-e3ea-4faa-ac76-6e43fd08e2d0" },
      cta: {
        link: "https://www.swiggy.com/city/pune/wefit-protein-bowls-salads-and-sandwiches-ventual-college-wadgaon-rest643841",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "681621",
        name: "LeanCrust Pizza- ThinCrust Experts",
        cloudinaryImageId:
          "RX_THUMBNAIL/IMAGES/VENDOR/2024/8/30/8cbb3bc5-e6af-4be5-8094-10dcdc02ac04_681621.jpg",
        locality: "Sun City",
        areaName: "Sinhgad Road",
        costForTwo: "₹300 for two",
        cuisines: ["Pizzas", "Italian", "Desserts"],
        avgRating: 4.8,
        parentId: "11216",
        avgRatingString: "4.8",
        totalRatingsString: "287",
        sla: {
          deliveryTime: 25,
          lastMileTravel: 3.6,
          serviceability: "SERVICEABLE",
          slaString: "20-30 mins",
          lastMileTravelString: "3.6 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: { nextCloseTime: "2024-11-20 02:00:00", opened: true },
        badges: {
          textExtendedBadges: [
            {
              iconId: "guiltfree/GF_Logo_android_3x",
              shortDescription: "options available",
              fontColor: "#7E808C",
            },
          ],
        },
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {
              badgeObject: [
                {
                  attributes: {
                    description: "",
                    fontColor: "#7E808C",
                    iconId: "guiltfree/GF_Logo_android_3x",
                    shortDescription: "options available",
                  },
                },
              ],
            },
          },
        },
        aggregatedDiscountInfoV3: { header: "50% OFF", subHeader: "UPTO ₹100" },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: { lottie: {}, video: {} },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
        externalRatings: { aggregatedRating: { rating: "--" } },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
      },
      analytics: { context: "seo-data-2b3cc11c-e3ea-4faa-ac76-6e43fd08e2d0" },
      cta: {
        link: "https://www.swiggy.com/city/pune/leancrust-pizza-thincrust-experts-sun-city-sinhgad-road-rest681621",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "622212",
        name: "MOJO Pizza - 2X Toppings",
        cloudinaryImageId:
          "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/24/295f1bfc-237b-4bd4-832b-a23fdf08f8aa_622212.JPG",
        locality: "SunCity",
        areaName: "Sinhgad Road",
        costForTwo: "₹250 for two",
        cuisines: ["Pizzas", "Italian", "Fast Food", "Desserts"],
        avgRating: 4.7,
        parentId: "11329",
        avgRatingString: "4.7",
        totalRatingsString: "742",
        sla: {
          deliveryTime: 25,
          lastMileTravel: 3.6,
          serviceability: "SERVICEABLE",
          slaString: "20-30 mins",
          lastMileTravelString: "3.6 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: { nextCloseTime: "2024-11-20 02:00:00", opened: true },
        badges: {
          textExtendedBadges: [
            {
              iconId: "guiltfree/GF_Logo_android_3x",
              shortDescription: "options available",
              fontColor: "#7E808C",
            },
          ],
        },
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {
              badgeObject: [
                {
                  attributes: {
                    description: "",
                    fontColor: "#7E808C",
                    iconId: "guiltfree/GF_Logo_android_3x",
                    shortDescription: "options available",
                  },
                },
              ],
            },
          },
        },
        aggregatedDiscountInfoV3: { header: "50% OFF", subHeader: "UPTO ₹100" },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: { lottie: {}, video: {} },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
        externalRatings: { aggregatedRating: { rating: "--" } },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
      },
      analytics: { context: "seo-data-2b3cc11c-e3ea-4faa-ac76-6e43fd08e2d0" },
      cta: {
        link: "https://www.swiggy.com/city/pune/mojo-pizza-2x-toppings-suncity-sinhgad-road-rest622212",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "720362",
        name: "Wendy's Burgers",
        cloudinaryImageId: "f1aa621021a2826088089b89842d4e7c",
        locality: "Datta nagar chowk",
        areaName: "AVDHOOT HIGHTS",
        costForTwo: "₹200 for two",
        cuisines: ["Burgers", "American", "Fast Food", "Snacks"],
        avgRating: 4.3,
        parentId: "972",
        avgRatingString: "4.3",
        totalRatingsString: "1.7K+",
        sla: {
          deliveryTime: 35,
          lastMileTravel: 2.7,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "2.7 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: { nextCloseTime: "2024-11-19 23:59:00", opened: true },
        badges: {
          textExtendedBadges: [
            {
              iconId: "guiltfree/GF_Logo_android_3x",
              shortDescription: "options available",
              fontColor: "#7E808C",
            },
          ],
        },
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {
              badgeObject: [
                {
                  attributes: {
                    description: "",
                    fontColor: "#7E808C",
                    iconId: "guiltfree/GF_Logo_android_3x",
                    shortDescription: "options available",
                  },
                },
              ],
            },
          },
        },
        aggregatedDiscountInfoV3: { header: "ITEMS", subHeader: "AT ₹89" },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: { lottie: {}, video: {} },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
        externalRatings: { aggregatedRating: { rating: "--" } },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
      },
      analytics: { context: "seo-data-2b3cc11c-e3ea-4faa-ac76-6e43fd08e2d0" },
      cta: {
        link: "https://www.swiggy.com/city/pune/wendys-burgers-datta-nagar-chowk-avdhoot-hights-rest720362",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "255146",
        name: "Faasos - Wraps, Rolls & Shawarma",
        cloudinaryImageId:
          "RX_THUMBNAIL/IMAGES/VENDOR/2024/7/28/eeaac9e1-ca4f-4c32-be92-d34272321a6c_255146.JPG",
        locality: "Datta nagar chowk",
        areaName: "Ambegaon",
        costForTwo: "₹200 for two",
        cuisines: [
          "Kebabs",
          "Fast Food",
          "Snacks",
          "American",
          "Healthy Food",
          "Desserts",
          "Beverages",
        ],
        avgRating: 4.2,
        parentId: "21809",
        avgRatingString: "4.2",
        totalRatingsString: "3.2K+",
        sla: {
          deliveryTime: 33,
          lastMileTravel: 2.7,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "2.7 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: { nextCloseTime: "2024-11-19 23:59:00", opened: true },
        badges: {
          textExtendedBadges: [
            {
              iconId: "guiltfree/GF_Logo_android_3x",
              shortDescription: "options available",
              fontColor: "#7E808C",
            },
          ],
        },
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {
              badgeObject: [
                {
                  attributes: {
                    description: "",
                    fontColor: "#7E808C",
                    iconId: "guiltfree/GF_Logo_android_3x",
                    shortDescription: "options available",
                  },
                },
              ],
            },
          },
        },
        aggregatedDiscountInfoV3: { header: "50% OFF", subHeader: "UPTO ₹100" },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: { lottie: {}, video: {} },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
        externalRatings: { aggregatedRating: { rating: "--" } },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
      },
      analytics: { context: "seo-data-2b3cc11c-e3ea-4faa-ac76-6e43fd08e2d0" },
      cta: {
        link: "https://www.swiggy.com/city/pune/faasos-wraps-rolls-and-shawarma-datta-nagar-chowk-ambegaon-rest255146",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "837979",
        name: "Pizza Project ",
        cloudinaryImageId: "f1b907b0b8f86c62e4fc347c6b1434e6",
        locality: "Datta nagar chowk",
        areaName: "AVDHOOT HIGHTS",
        costForTwo: "₹400 for two",
        cuisines: ["Pizzas", "Italian", "Desserts", "Beverages"],
        avgRating: 3.8,
        parentId: "497031",
        avgRatingString: "3.8",
        totalRatingsString: "31",
        sla: {
          deliveryTime: 35,
          lastMileTravel: 2.7,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "2.7 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: { nextCloseTime: "2024-11-19 23:59:00", opened: true },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        aggregatedDiscountInfoV3: { header: "60% OFF", subHeader: "UPTO ₹110" },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: { lottie: {}, video: {} },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
        externalRatings: { aggregatedRating: { rating: "--" } },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
      },
      analytics: { context: "seo-data-2b3cc11c-e3ea-4faa-ac76-6e43fd08e2d0" },
      cta: {
        link: "https://www.swiggy.com/city/pune/pizza-project-datta-nagar-chowk-avdhoot-hights-rest837979",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "801416",
        name: "Makhani Darbar",
        cloudinaryImageId: "c583da4b69d264ffe705e5918fad0e98",
        locality: "Katraj FC",
        areaName: "Datta nagar chowk",
        costForTwo: "₹500 for two",
        cuisines: [
          "Biryani",
          "North Indian",
          "Kebabs",
          "Mughlai",
          "Beverages",
          "Desserts",
        ],
        avgRating: 3.4,
        parentId: "478595",
        avgRatingString: "3.4",
        totalRatingsString: "28",
        sla: {
          deliveryTime: 36,
          lastMileTravel: 2.7,
          serviceability: "SERVICEABLE",
          slaString: "35-40 mins",
          lastMileTravelString: "2.7 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: { nextCloseTime: "2024-11-19 23:59:00", opened: true },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹399",
          discountTag: "FLAT DEAL",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: { lottie: {}, video: {} },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
        externalRatings: { aggregatedRating: { rating: "--" } },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
      },
      analytics: { context: "seo-data-2b3cc11c-e3ea-4faa-ac76-6e43fd08e2d0" },
      cta: {
        link: "https://www.swiggy.com/city/pune/makhani-darbar-katraj-fc-datta-nagar-chowk-rest801416",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "678954",
        name: "Dum Safar Biryani",
        cloudinaryImageId: "1154cffac2453eb0bf7fdda7e5ea1659",
        locality: "Horizon Mall",
        areaName: "Sinhgad road",
        costForTwo: "₹500 for two",
        cuisines: ["Biryani", "Kebabs", "Tandoor", "Indian", "Desserts"],
        avgRating: 4.3,
        parentId: "351013",
        avgRatingString: "4.3",
        totalRatingsString: "192",
        sla: {
          deliveryTime: 36,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "35-40 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: { nextCloseTime: "2024-11-19 23:30:00", opened: true },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        aggregatedDiscountInfoV3: { header: "ITEMS", subHeader: "AT ₹139" },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: { lottie: {}, video: {} },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
        externalRatings: { aggregatedRating: { rating: "--" } },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
      },
      analytics: { context: "seo-data-2b3cc11c-e3ea-4faa-ac76-6e43fd08e2d0" },
      cta: {
        link: "https://www.swiggy.com/city/pune/dum-safar-biryani-horizon-mall-sinhgad-road-rest678954",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "566457",
        name: "Faasos' Signature Wraps & Rolls",
        cloudinaryImageId: "c583ca6ce40b426797a78ae2ac91f2ec",
        locality: "Datta nagar chowk",
        areaName: "AVDHOOT HIGHTS",
        costForTwo: "₹350 for two",
        cuisines: [
          "Fast Food",
          "Snacks",
          "North Indian",
          "Desserts",
          "Beverages",
        ],
        avgRating: 4.2,
        parentId: "340366",
        avgRatingString: "4.2",
        totalRatingsString: "131",
        sla: {
          deliveryTime: 35,
          lastMileTravel: 2.7,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "2.7 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: { nextCloseTime: "2024-11-19 23:59:00", opened: true },
        badges: {
          textExtendedBadges: [
            {
              iconId: "guiltfree/GF_Logo_android_3x",
              shortDescription: "options available",
              fontColor: "#7E808C",
            },
          ],
        },
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {
              badgeObject: [
                {
                  attributes: {
                    description: "",
                    fontColor: "#7E808C",
                    iconId: "guiltfree/GF_Logo_android_3x",
                    shortDescription: "options available",
                  },
                },
              ],
            },
          },
        },
        aggregatedDiscountInfoV3: { header: "50% OFF", subHeader: "UPTO ₹100" },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: { lottie: {}, video: {} },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
        externalRatings: { aggregatedRating: { rating: "--" } },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
      },
      analytics: { context: "seo-data-2b3cc11c-e3ea-4faa-ac76-6e43fd08e2d0" },
      cta: {
        link: "https://www.swiggy.com/city/pune/faasos-signature-wraps-and-rolls-datta-nagar-chowk-avdhoot-hights-rest566457",
        type: "WEBLINK",
      },
    },
];